### PR TITLE
Revert "Move truffle-hdwallet-provider to dev dependencies"

### PR DESCRIPTION
**Pull request by Aniket-Engg**
Reverts Aniket-Engg/sol-verifier#45

### CODE REVIEW

**Comment by Aniket-Engg** [comment]
@ukstv Tests were failing on merge, So i have to revert it. See CI: https://travis-ci.com/Aniket-Engg/sol-verifier/jobs/251107947

Please check if tests are working locally as environment variables do not work for your PR. You can raise a new one with your changes.

**Comment by Aniket-Engg** [comment]
Thanks @ukstv , it is passing now. Probably last time it was failing because of unstability of rinkeby network or EtherScan APIs. Thanks again for your contribution.

**Comment by ukstv** [comment]
Yehaa! Thanks to you for the great tool!

**Comment by ukstv** [comment]
Hey, @Aniket-Engg mind releasing an updated version to NPM, please?

**Comment by Aniket-Engg** [comment]
@ukstv  done

**Comment by ukstv** [comment]
Super! Thanks!

**Pull request merged**
